### ISSUE TITLE
conflicting declarations for template

### ISSUE THREAD

**Issue by LukasChenChen** [iszczesniak/yen#1]
Hi, I've found that in yen_ksp.cc and yen_ksp.h, Edge, Vertex, Path and Result are defined twice.
If remove the above definition,  in yen_ksp.cc line 101:` typedef Result<graph, int> result` should be typedef Result<int , graph>result as a result. I'm not sure if the conflicts has something to do with my compiler or library, mine is C++14 an gcc 7.5.0

**Comment by iszczesniak** [comment]
Hi,

Thanks for reporting the problem.

Types in `yen_ksp.cc` and `yen_ksp.hpp` define different types, so they are not redefinitions: file `yen_ksp.hpp` defines types in the `boost` namespace, and `yen_ksp.cc` in the global namespace.

However, definitions for the `Result` type are different, and that's an inconsistency which I just fixed in revision d12b15ef79a71a5bda931bc53a554da127346a11.

So if in your code you used them both (`::Result` and `boost::Result`) interchangeably (thinking they are the same), then you should have gotten some error.

The code compiles fine for me before and after the commit.  I'm using GCC 10.1.0.


Best,
Irek

**Comment by LukasChenChen** [comment]
Hi Irek

Thanks for coming back to me. Sorry I misread the code. I adapt your code to my own module, so there was some little problems but nvm.

best,
chen

**Comment by iszczesniak** [comment]
Hi Chen,

OK, thanks. I'm closing the issue.

Best,
Irek
